config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do 
    get 'login' => :new 
    post 'login' => :create 
    delete 'logout' => :destroy
  end

  match 'questions' => 'other_pages#questions'
  match 'news' => 'other_pages#news'
  match 'contacts' => 'other_pages#contacts'
  

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  resources :products do
     get :who_bought, :on => :member
  end

  get "store/index"

 

    root :to => "store#index", :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html> 
<head> 
  <title>Pragprog Books Online Store</title> 
<!-- START:stylesheet --> 
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %><!-- <label id="code.slt"/> --> 
<!-- END:stylesheet --> 
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> --> 
</head> 
<body id="store"> 
  <div id="banner"> 
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %><!-- <label id="code.depot.e.title"/> --> 
  </div> 
  <div id="columns"> 
    <div id="side">
	  <% if @cart %> 
  	    <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
		  <%= render @cart %>
	    <% end %>
	  <% end %>
	
      <%= link_to 'Home', store_path %><br />
      <%= link_to 'Questions', 'questions' %><br />
      <%= link_to 'News', 'news' %><br />
      <%= link_to 'Contacts', 'contacts' %><br />

      <% if session[:user_id] %>
		<br />
		<%= link_to 'Orders', orders_path %><br />
		<%= link_to 'Products', products_path %><br />
		<%= link_to 'Users', users_path %><br />
		<br />
		<%= button_to 'Logout', logout_path, :method => :delete %>
	  <% end %>
		
    </div> 
    <div id="main"> 
      <%= yield %><!-- <label id="code.depot.e.include"/> --> 
    </div> 
  </div> 
</body> 
</html>